routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('home', function ()
{
    return redirect('/');
});

Route::get('/', function ()
{
    return view('index');
})->name('home');

Route::get('authors', function ()
{
    return view('author-list');
})->name('author.list');

Route::get('books', function ()
{
    return view('book-list');
})->name('book.list');

Route::get('user', function ()
{
    return view('user', ['user' => auth()->user()->user]);
})->middleware('auth')->name('user');

Route::get('authors/{id}', 'AuthorController@authorInfo')->name('author.info');
Route::get('books/{id}', 'BookController@bookInfo')->name('book.info');

Route::post('comments/create', 'CommentController@commentCreate')->name('comment.create');
Route::post('comments/delete', 'CommentController@commentDelete')->name('comment.delete');

Route::post('user/update', 'UserController@userUpdate')->middleware('auth')->name('user.update');

Route::prefix('admin')->name('admin.')->middleware('admin')->group(function ()
{
    Route::get('/', function ()
    {
        return view('admin.home');
    })->name('home');

    Route::get('authors', function ()
    {
        return view('admin.author-list');
    })->name('author.list');

    Route::get('books', function ()
    {
        return view('admin.book-list');
    })->name('book.list');

    Route::get('authors/new', function ()
    {
        return view('admin.author-new');
    })->name('author.new');

    Route::get('books/new/{author_id?}', function ($author_id = 0)
    {
        return view('admin.book-new', ['author_id' => $author_id]);
    })->name('book.new');

    Route::get('comments', function ()
    {
        return view('admin.comments-all');
    })->name('comment.list');

    Route::get('users', function ()
    {
        return view('admin.user-list');
    })->name('user.list');

    Route::get('authors/{id}', 'AdminController@authorInfo')->name('author.info');
    Route::get('books/{id}', 'AdminController@bookInfo')->name('book.info');
    Route::get('users/{id}', 'AdminController@userInfo')->name('user.info');

    Route::post('authors/delete', 'AdminController@authorDelete')->name('author.delete');
    Route::post('books/delete', 'AdminController@bookDelete')->name('book.delete');
    Route::post('comments/delete', 'AdminController@commentDelete')->name('comment.delete');

    Route::post('authors/update', 'AdminController@authorUpdate')->name('author.update');
    Route::post('books/update', 'AdminController@bookUpdate')->name('book.update');
    Route::post('users/update', 'AdminController@userUpdate')->name('user.update');

    Route::post('authors/create', 'AdminController@authorCreate')->name('author.create');
    Route::post('books/create', 'AdminController@bookCreate')->name('book.create');

    Route::post('users/unlink', 'AdminController@unlinkSocial')->name('unlink.social');
});

Auth::routes();

Route::get('login/github', 'Auth\SocialController@github')->name('login.github');
Route::get('login/github/callback', 'Auth\SocialController@githubCallback');

Route::get('login/google', 'Auth\SocialController@google')->name('login.google');
Route::get('login/google/callback', 'Auth\SocialController@googleCallback');

Route::post('user/unlink', 'UserController@unlinkSocial')->name('user.unlink.social');

resources/views/admin/author-info.blade.php
@extends('layouts.admin')

@section('title', __('admin.pages.authors'))

@push('scripts')
    <script type="text/javascript" src="{{ mix('js/app.js') }}"></script>
    <script type="text/javascript">
        let route_author_update = "{{ route('admin.author.update') }}";
        let route_author_delete = "{{ route('admin.author.delete') }}";
        let author_id = "{{ $author->id }}";
    </script>
@endpush

@section('content')
    <table style="max-width: 600px;">
        <tr>
            <td style="width: 100px;">{{ __('author.last_name') }}:</td>
            <td style="width: 494px;">
                <input id="last_name" class="edited-data" type="text" value="{{ $author->last_name }}" disabled>
            </td>
        </tr>
        <tr>
            <td>{{ __('author.first_name') }}:</td>
            <td>
                <input id="first_name" class="edited-data" type="text" value="{{ $author->first_name }}" disabled>
            </td>
        </tr>
        <tr>
            <td>{{ __('author.birth_date') }}:</td>
            <td>
                <input id="birthday" class="edited-data" type="date" value="{{ \Carbon\Carbon::parse($author->birth_date)->format('Y-m-d') }}" disabled>
            </td>
        </tr>
        <tr class="tr-button btn-edit">
            <td colspan="2">
                {{ __('Edit Info') }}
            </td>
        </tr>
        <tr style="display: none;" class="tr-button btn-save author-save">
            <td colspan="2">
                {{ __('Save') }}
            </td>
        </tr>
        <tr style="display: none;" class="tr-button btn-cancel">
            <td colspan="2">
                {{ __('Cancel editing') }}
            </td>
        </tr>
        <tr class="tr-button author-delete">
            <td colspan="2">{{ __('Delete this author') }}</td>
        </tr>
        <tr class="tr-button">
            <td colspan="2">
                <a style="display: block;" href="{{ route('admin.book.new', $author->id) }}">{{ __('Add new book') }}</a>
            </td>
        </tr>
    </table>
    <div style="width: 100%; margin: 10px 0; font-size: 18px; font-weight: bold;">{{ __('main.book_list') }}:</div>
    <div class="list big-list">
        @forelse($author->books->sortBy('id') as $book)
            <a href="{{ route('admin.book.info', $book->id) }}" class="list-element">
                <div class="list-element-text">{{ $book->title }}</div>
                <div class="list-relationship-quantity">
                    <div class="quantity-number">
                        {{ $book->commentaries->count() }}
                    </div>
                    <div class="quantity-caption">{{ __('index.caption_comments') }}</div>
                </div>
            </a>
        @empty
            <div class="list-element">
                <div class="list-element-text" style="width: 100%; text-align: center;">{{ __('Books not found') }}</div>
            </div>
        @endforelse
    </div>
@endsection

resources/views/admin/author-list.blade.php
@extends('layouts.admin')

@section('title', __('admin.pages.authors'))

@section('content')
    <a href="{{ route('admin.author.new') }}" class="btn" style="margin: 0 auto; width: 300px; text-align: center;">{{ __('Add new author') }}</a>
    <div class="list big-list">
        @foreach(\App\Author::all()->sortBy('id') as $author)
            <a href="{{ route('admin.author.info', $author->id) }}" class="list-element">
                <div class="list-element-text">{{ $author->first_name }} {{ $author->last_name }}</div>
                <div class="list-relationship-quantity">
                    <div class="quantity-number">
                        {{ $author->books->count() }}
                    </div>
                    <div class="quantity-caption">{{ __('index.caption_books') }}</div>
                </div>
            </a>
        @endforeach
    </div>
@endsection

resources/views/admin/author-new.blade.php
@extends('layouts.admin')

@section('title', __('admin.pages.authors'))

@push('scripts')
    <script type="text/javascript" src="{{ mix('js/app.js') }}"></script>
    <script type="text/javascript">
        let route_author_create = "{{ route('admin.author.create') }}";
    </script>
@endpush

@section('content')
    <table style="max-width: 600px;">
        <tr>
            <td style="width: 100px;">{{ __('author.last_name') }}:</td>
            <td style="width: 494px;">
                <input id="last_name" type="text" value="">
            </td>
        </tr>
        <tr>
            <td>{{ __('author.first_name') }}:</td>
            <td>
                <input id="first_name" type="text" value="">
            </td>
        </tr>
        <tr>
            <td>{{ __('author.birth_date') }}:</td>
            <td>
                <input id="birthday" type="date" value="">
            </td>
        </tr>
        <tr class="tr-button author-create">
            <td colspan="2">
                {{ __('Save') }}
            </td>
        </tr>
    </table>
@endsection

resources/views/admin/book-info.blade.php
@extends('layouts.admin')

@section('title', __('admin.pages.books'))

@push('styles')
    <link rel="stylesheet" href="{{ mix('css/comments.css') }}">
@endpush

@push('scripts')
    <script type="text/javascript" src="{{ mix('js/app.js') }}"></script>
    <script type="text/javascript">
        let route_comment_create = "{{ route('comment.create') }}";
        let route_comment_delete = "{{ route('admin.comment.delete') }}";
        let route_book_delete = "{{ route('admin.book.delete') }}";
        let route_book_update = "{{ route('admin.book.update') }}";
        let book_id = "{{ $book->id }}";
    </script>
@endpush

@section('content')
    <table style="max-width: 600px;">
        <tr>
            <td style="width: 100px;">{{ __('book.title') }}:</td>
            <td style="font-weight: bold; width: 494px;">
                <input id="title" class="edited-data" type="text" value="{{ $book->title }}" disabled>
            </td>
        </tr>
        <tr>
            <td>{{ __('book.author') }}:</td>
            <td>
                <a href="{{ route('admin.author.info', $book->author->id) }}" style="color: blue; font-weight: bold;">{{ $book->author->first_name }} {{ $book->author->last_name }}</a>
                <select id="author_id" class="edited-data" style="display: block;" disabled>
                    @foreach(\App\Author::all()->sortBy('id') as $option)
                        <option value="{{ $option->id }}" @if($option->id == $book->author->id) selected @endif>{{ $option->first_name }} {{ $option->last_name }}</option>
                    @endforeach
                </select>
            </td>
        </tr>
        <tr>
            <td style="vertical-align: top;">{{ __('book.description') }}:</td>
            <td>
                <div id="description-text">{{ $book->description }}</div>
                <textarea style="display:none; width: 100%; height: 70px;" id="description-area" class="edited-data">{{ $book->description }}</textarea>
            </td>
        </tr>
        <tr class="tr-button book-edit">
            <td colspan="2">
                {{ __('Edit Info') }}
            </td>
        </tr>
        <tr style="display: none;" class="tr-button btn-save book-save">
            <td colspan="2">
                {{ __('Save') }}
            </td>
        </tr>
        <tr style="display: none;" class="tr-button btn-cancel book-cancel">
            <td colspan="2">
                {{ __('Cancel editing') }}
            </td>
        </tr>
        <tr class="tr-button book-delete">
            <td colspan="2">{{ __('Delete this book') }}</td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center; font-weight: bold; background: #ccc;">{{ __('Comments') }}</td>
        </tr>
        @includeWhen($comments_tree, 'admin.comment', ['comments_tree' => $comments_tree])
        @auth
            <tr>
                <td colspan="2">
                    <div class="leave-comment">
                        <a class="leave-comment-title">&gt; {{ __('Leave a comment') }} &lt;</a>
                    </div>
                </td>
            </tr>
        @endauth
    </table>
@endsection

resources/views/admin/book-list.blade.php
@extends('layouts.admin')

@section('title', __('admin.pages.books'))

@section('content')
    <a href="{{ route('admin.book.new') }}" class="btn" style="margin: 0 auto; width: 300px; text-align: center;">{{ __('Add new book') }}</a>
    <div class="list big-list">
        @foreach(\App\Book::all()->sortBy('id') as $book)
            <a href="{{ route('admin.book.info', $book->id) }}" class="list-element">
                <div class="list-element-text">{{ $book->title }}</div>
                <div class="list-relationship-quantity">
                    <div class="quantity-number">
                        {{ $book->commentaries->count() }}
                    </div>
                    <div class="quantity-caption">{{ __('index.caption_comments') }}</div>
                </div>
            </a>
        @endforeach
    </div>
@endsection

resources/views/admin/book-new.blade.php
@extends('layouts.admin')

@section('title', __('admin.pages.books'))

@push('styles')
    <link rel="stylesheet" href="{{ mix('css/comments.css') }}">
@endpush

@push('scripts')
    <script type="text/javascript" src="{{ mix('js/app.js') }}"></script>
    <script type="text/javascript">
        let route_book_create = "{{ route('admin.book.create') }}";
    </script>
@endpush

@section('content')
    <table style="max-width: 600px;">
        <tr>
            <td style="width: 100px;">{{ __('book.title') }}:</td>
            <td style="font-weight: bold; width: 494px;">
                <input id="title" type="text" value="">
            </td>
        </tr>
        <tr>
            <td>{{ __('book.author') }}:</td>
            <td>
                <select id="author_id" style="display: block;">
                    @foreach(\App\Author::all()->sortBy('id') as $option)
                        <option value="{{ $option->id }}" @if(!empty($author_id) && $option->id == $author_id) selected @endif>{{ $option->first_name }} {{ $option->last_name }}</option>
                    @endforeach
                </select>
            </td>
        </tr>
        <tr>
            <td style="vertical-align: top;">{{ __('book.description') }}:</td>
            <td>
                <textarea style="width: 100%; height: 70px;" id="description-area"></textarea>
            </td>
        </tr>
        <tr class="tr-button book-create">
            <td colspan="2">
                {{ __('Save') }}
            </td>
        </tr>
    </table>
@endsection

resources/views/admin/comment-list.blade.php
@forelse($comments_tree as $comment_data)
    <tr id="comment_{{ $comment_data->id }}">
        <td colspan="2">
            <div class="comment">
                <div class="comment-header">
                    <a href="{{ route('admin.book.info', $comment_data->book->id) }}#comment_{{ $comment_data->id }}">Comment #{{ $comment_data->id }}</a>
                    @if($comment_data->parent_comment)
                        replied to <a href="{{ route('admin.book.info', $comment_data->book->id) }}#comment_{{ $comment_data->parent_comment }}">comment #{{$comment_data->parent_comment}}</a>
                    @endif
                </div>
                <div class="comment-body">{{ $comment_data->comment }}</div>
                <div class="comment-footer">
                    <a class="delete-link" data-id="{{ $comment_data->id }}">{{ __('Delete') }}</a>
                    {{ $comment_data->created_at }}
                </div>
            </div>
        </td>
    </tr>
@empty
    <tr>
        <td colspan="2" style="text-align: center">{{ __('No comments') }}</td>
    </tr>
@endforelse

resources/views/admin/comment.blade.php
@foreach($comments_tree as $comment_data)
    <tr id="comment_{{ $comment_data->self->id }}">
        <td colspan="2">
            <div class="comment depth_{{ $comment_data->depth }}">
                <div class="comment-header">Comment #{{ $comment_data->self->id }}
                    @if($comment_data->self->parent_comment)
                        replied to <a href="#comment_{{ $comment_data->self->parent_comment }}">comment #{{$comment_data->self->parent_comment}}</a>
                    @endif
                </div>
                <div class="comment-body">{{ $comment_data->self->comment }}</div>
                <div class="comment-footer">
                    @auth
                        @if($comment_data->depth < 2)
                            <a class="reply-link" data-id="{{ $comment_data->self->id }}">{{ __('Reply') }}</a>
                        @endif
                        <a class="delete-link" data-id="{{ $comment_data->self->id }}">{{ __('Delete') }}</a>
                    @endauth
                    {{ $comment_data->self->created_at }}
                </div>
            </div>
        </td>
    </tr>
    @includeWhen($comment_data->children, 'admin.comment', ['comments_tree' => $comment_data->children])
@endforeach

resources/views/admin/comments-all.blade.php
@extends('layouts.admin')

@section('title', __('main.pages.user'))

@push('styles')
    <link rel="stylesheet" href="{{ mix('css/comments.css') }}">
@endpush

@push('scripts')
    <script type="text/javascript" src="{{ mix('js/app.js') }}"></script>
    <script type="text/javascript">
        let route_comment_delete = "{{ route('comment.delete') }}";
    </script>
@endpush

@section('content')
    <table style="max-width: 600px;">
        <tr>
            <td colspan="2" style="text-align: center; font-weight: bold; background: #ccc; width: 100%;">{{ __('Comment List') }}</td>
        </tr>
        @include('admin.comment-list', ['comments_tree' => \App\Comment::all()->sortByDesc('id')])
    </table>
@endsection

resources/views/admin/home.blade.php
@extends('layouts.admin')

@section('title', __('admin.pages.home'))

@push('styles')
    <link rel="stylesheet" href="{{ mix('css/index.css') }}">
@endpush

@section('content')
    <div class="site-description">
        This is an Admin Panel.
    </div>
    <div class="latest-entries">
        <div class="list twin-list">
            <div class="list-title">{{ __('Latest comments') }}</div>
            @forelse(\App\Comment::all()->sortByDesc('id')->take(5) as $comment)
                <a href="{{ route('admin.book.info', $comment->book_id) }}#comment_{{ $comment->id }}" class="list-element">
                    <div class="list-element-text">{{ $comment->comment }}</div>
                </a>
            @empty
                <div class="list-element">
                    <div class="list-element-text" style="width: 100%; text-align: center;">{{ __('No comments') }}</div>
                </div>
            @endforelse
            <a href="{{ route('admin.comment.list') }}" class="full-list-link">&gt; {{ __('All comments') }} &lt;</a>
        </div>
    </div>
@endsection

resources/views/admin/user-info.blade.php
@extends('layouts.admin')

@section('title', __('admin.pages.users'))

@push('styles')
    <link rel="stylesheet" href="{{ mix('css/comments.css') }}">
@endpush

@push('scripts')
    <script type="text/javascript" src="{{ mix('js/app.js') }}"></script>
    <script type="text/javascript">
        let route_profile_update = "{{ route('admin.user.update') }}";
        let route_comment_delete = "{{ route('admin.comment.delete') }}";
        let route_unlink_social  = "{{ route('admin.unlink.social') }}";
        let user_id = "{{ $user->id }}";
    </script>
@endpush

@section('content')
    <table style="max-width: 600px;">
        <tr>
            <td style="width: 100px;">{{ __('Last name') }}:</td>
            <td style="font-weight: bold; width: 494px;">
                <input id="last_name" class="edited-data" type="text" value="{{ $user->last_name }}" disabled>
            </td>
        </tr>
        <tr>
            <td>{{ __('First name') }}:</td>
            <td style="font-weight: bold">
                <input id="first_name" class="edited-data" type="text" value="{{ $user->first_name }}" disabled>
            </td>
        </tr>
        <tr>
            <td>{{ __('E-mail') }}:</td>
            <td style="font-weight: bold">
                <input id="email" class="edited-data" type="email" value="{{ $user->email }}" disabled>
            </td>
        </tr>
        <tr>
            <td>{{ __('Birthday') }}:</td>
            <td style="font-weight: bold">
                <input id="birthday" class="edited-data" type="date" value="{{ \Carbon\Carbon::parse($user->birth_date)->format('Y-m-d') }}" disabled>
            </td>
        </tr>
        <tr>
            <td>{{ __('GitHub') }}</td>
            <td>
                @if($user->entryPoints->where('type', \App\EntryPoint::GITHUB_REG)->first())
                    <div class="btn admin-social-unlink" social-type="{{ \App\EntryPoint::GITHUB_REG }}">{{ __('Unlink') }}</div>
                @else
                    {{ __('Not linked') }}
                @endif
            </td>
        </tr>
        <tr>
            <td>{{ __('Google') }}</td>
            <td>
                @if($user->entryPoints->where('type', \App\EntryPoint::GOOGLE_REG)->first())
                    <div class="btn admin-social-unlink" social-type="{{ \App\EntryPoint::GOOGLE_REG }}">{{ __('Unlink') }}</div>
                @else
                    {{ __('Not linked') }}
                @endif
            </td>
        </tr>
        <tr class="tr-button btn-edit">
            <td colspan="2">
                {{ __('Edit Info') }}
            </td>
        </tr>
        <tr style="display: none;" class="tr-button btn-save user-update">
            <td colspan="2">
                {{ __('Save') }}
            </td>
        </tr>
        <tr style="display: none;" class="tr-button btn-cancel">
            <td colspan="2">
                {{ __('Cancel editing') }}
            </td>
        </tr>
        @includeWhen($user->commentaries, 'admin.comment-list', ['comments_tree' => $user->commentaries->sortBy('id')])
    </table>
@endsection

resources/views/admin/user-list.blade.php
@extends('layouts.admin')

@section('title', __('admin.pages.users'))

@section('content')
    <div class="list big-list">
        @foreach(\App\User::all()->sortBy('id') as $user)
            <a href="{{ route('admin.user.info', $user->id) }}" class="list-element">
                <div class="list-element-text">{{ $user->first_name }} {{ $user->last_name }}</div>
                <div class="list-relationship-quantity">
                    <div class="quantity-number">
                        {{ $user->commentaries->count() }}
                    </div>
                    <div class="quantity-caption">{{ __('index.caption_comments') }}</div>
                </div>
            </a>
        @endforeach
    </div>
@endsection